name: Sync to Gitee

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 在 Settings->Secrets 配置 GITEE_SSH_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
        with:
          # GitHub 源仓库地址
          source-repo: git@github.com:yiyungent/Dragonfly.git
          # Gitee 目标仓库地址
          destination-repo: git@gitee.com:yiyungent/Dragonfly.git
